### ISSUE TITLE
not moving further

### ISSUE THREAD

**Issue by Chirag99786** [Serhiodev/Aptos_Bluemove_mint_bot#1]
after running bot there is only one option selecting wallet not moving forward and program stops
![bot bug](https://user-images.githubusercontent.com/88233375/200136578-78587d85-63cf-4734-86d7-e3137e0dd90c.png)

**Comment by Serhiodev** [comment]
Working on a fix, thank you.

**Comment by Chirag99786** [comment]
how i can contact you ?
